#!/bin/bash
set -euo pipefail
home="$(realpath "$(realpath "${BASH_SOURCE[0]}" | xargs dirname)")"
cd "$home"

#-----------------------------------------------------------------------------------------------------------
source ./lib.sh
info "$0" "$@"


whisper 'STEP 1 --------------------------------------------------------------------------------------------'
procure_package "$sqltfmki_path" "$sqltfmki_url"
whisper 'STEP 2 --------------------------------------------------------------------------------------------'
build_sqlite_for_mingkwai_ime
whisper 'STEP 3 --------------------------------------------------------------------------------------------'
procure_package "$bsql3_path" "$bsql3_url"
whisper 'STEP 4 --------------------------------------------------------------------------------------------'
build_better_sqlite3_with_sqlite_for_mingkwai_ime "$sqltfmki_path"
whisper 'STEP 5 --------------------------------------------------------------------------------------------'
link_better_sqlite3




