#!/bin/bash
set -euo pipefail
home="$(realpath "$(realpath "${BASH_SOURCE[0]}" | xargs dirname)")"
cd "$home"

#-----------------------------------------------------------------------------------------------------------
source ./lib.sh
info "$0" "$@"
link_better_sqlite3

